routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('category', 'CategoryController');
Route::resource('accountingbook', 'AccountingBookController');

app/AccountingBook.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AccountingBook extends Model
{
    protected $fillable = [

        'id', 'concept','date', 'amount', 'type', 'category_id'
    ];

    public function category() 
    { 
    	return $this->belongsTo('App\Category');
    	
    }
}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [

        'id', 'name','description','type'
    ];


    public function category() 
    { 
    	return $this->hasMany('App\Category');
    	
    }
}

app/Institute.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Institute extends Model
{
    protected $fillable = [
        'name', 'run', 'address','phone','amount_day_delay',
    ];

    public function user()
    {
        
        return $this->belongsTo('App\User');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'type', 'status', 'institute_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function institute()
    {
        
        return $this->belongsTo('App\Institute');
    }
}

app/Http/Controllers/AccountingBookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
Use App\AccountingBook;
use App\Category;
class AccountingBookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $accountingbook=Accountingbook::all();
        return view('accountingbook.index')->with(['accountingbook'=>$accountingbook]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()

    {
        $category=Category::all();

         return view('accountingbook.create')->with(['category'=>$category]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
          AccountingBook::create($request->all());

         return redirect()->route('accountingbook.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $accountingbook=AccountingBook::find($id);
         return view('accountingbook.edit')->with(['accountingbook'=>$accountingbook]);   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\AccountingBook;

class CategoryController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories=Category::all();
        return view('category.index')->with(['categories'=>$categories]);

    }

    public function create()
    {
         return view('category.create');
    }   

     public function store(Request $request)
    {
        Category::create($request->all());

         return redirect()->route('category.index');
    }   
      public function edit($id)
    {
        $category=Category::find($id);
         return view('category.edit')->with(['category'=>$category]);
    }   

    public function update(Request $request,$id)
    {
        $category = Category::find($id);

        $category->fill(request()->all());

        $category->save();
        
        return redirect()->route('category.index');
    }



    public function show()
    {
        return view('category.show') -> with(['id' => request() -> id]);
    }

    public function destroy($id)
    {
        AccountingBook::where('category_id', $id)->delete();
        
        $category = Category::destroy($id); 

        return redirect()->route('category.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/accountingbook/create.blade.php
@extends('layouts.master')

@section('content')
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                          <div class="col-md-12">
                            <div class="card card-plain">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Crear - Libro contable</h4>
                                    <p class="category">Creación de libro contable</p>
                                    
                                </div>
                                <div class="pull-left">
                                         <a href="{{ route('accountingbook.index')}}" class="btn btn-warning" id="addButton">Atrás</a>
                                    </div>
                                    <br>
                                    <br>
                                    <br>   
                                    <form id="form-validation" action="{{ route('accountingbook.store') }}" method="POST"  enctype="multipart/form-data" >
                                      {{ csrf_field() }}
                                      <div class="form-group">
                                         <label for="exampleInput1" class="bmd-label-floating">Concepto</label>
                                         <input type="text" name="concept" class="form-control" id="concept">
                                         <span class="bmd-help">Concepto del libro contable</span>
                                      </div>
                                      <div class="form-group">
                                         <label for="exampleInput1" class="bmd-label-floating">Fecha</label>
                                         <input name="date" type="date" class="form-control" id="date">
                                         <span class="bmd-help">Fecha</span>
                                      </div>
                                     <div class="form-group">
                                        <label for="type">tipo</label>
                                        <select name="type" class="form-control" id="type">
                                          <option value="ingreso">INGRESO</option>
                                          <option value="egreso">EGRESO</option>
                                        </select>
                                        </div>
                                        <div class="form-group">
                                          <label for="catalago" class="control-label">Catalago</label>
                                            <select id="category_id" name="category_id" class="form-control">
                                              <option value="">Seleccione un catalago...</option>
                                                @foreach($category as $element)
                                                  <option value="{{ $element->id }}">{{ $element->name }}</option>
                                                    @endforeach
                                                </select>
                                          </div>
                                    <div class="form-group">
                                         <label for="exampleInput1" class="bmd-label-floating">Monto</label>
                                         <input name="amount" type="text" class="form-control" id="amount">
                                         <span class="bmd-help">Monto</span>
                                      </div>
                                      <button type="submit" class="btn btn-primary">Guardar</button>
                                    </form> 
                               
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div> 
        </div>
  

@endsection

resources/views/accountingbook/edit.blade.php
@extends('layouts.master')

@section('content')
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                          <div class="col-md-12">
                            <div class="card card-plain">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Editar - Libro contable</h4>
                                    <p class="category">Edición del Libro contable</p>
                                    
                                </div>
                                <div class="pull-left">
                                         <a href="{{route('accountingbook.index')}}" class="btn btn-warning" id="addButton">Atrás</a>
                                    </div>
                                    <br>
                                    <br>
                                    <br>   
                                    <form action="{{ route('accountingbook.update', $accountingbook->id) }}" method="POST">
                                      {{ csrf_field() }}
                                      <div class="form-group">
                                         <label for="exampleInput1" class="bmd-label-floating">Concepto</label>
                                         <input name="concept" type="text" class="form-control" id="description">
                                         <span class="bmd-help">Concepto</span>
                                      </div>
                                     <div class="form-group">
                                        <label for="type">tipo</label>
                                        <select name="type" class="form-control" id="type">
                                          <option value="ingreso">Ingreso</option>
                                          <option value="egreso">Egreso</option>
                                        </select>
                                    </div>
                                      <button type="submit" class="btn btn-primary">Guardar</button>
                                    </form> 
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div> 
        </div>
  

@endsection

resources/views/accountingbook/index.blade.php
@extends('layouts.master')

@section('content')
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                          <div class="col-md-12">
                            <div class="card card-plain">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Libro Contable</h4>
                                    <p class="category">Listado de libro contable</p>
                                    
                                </div>
                                <div class="pull-left">
                                         <a href="{{route('accountingbook.create')}}" class="btn btn-primary" id="addButton">Nuevo</a>
                                    </div>
                                    <br>
                                    <br>
                                    <br>    
                                <div class="card-content table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <th>Codigo</th>
                                            <th>Concepto</th>
                                            <th>Tipo</th>
                                            <th>Monto</th>
                                            <th>Categoria</th>
                                            <th>Acciones</th>
                                        </thead>
                                        <tbody>
                                        @foreach($accountingbook as $element)
                                        <tr>
                                            <td>{{$element -> id}}</td>
                                            <td>{{$element -> concept}}</td> 
                                            <td>{{$element -> type}}</td>  
                                            <td>{{$element -> amount}}</td> 
                                            <td>{{$element ->category->name}}</td>
                                            <td><a href="{{route('accountingbook.edit',$element-> id)}}"><i class="material-icons text-info">mode_edit</i></a> 
                                            <a href="{{route('accountingbook.destroy', $element ->id )}}"><i class="material-icons text-danger" >delete</i></a></td>             
                                        </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div> 
        </div>
  

@endsection

resources/views/category/create.blade.php
@extends('layouts.master')

@section('content')
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                          <div class="col-md-12">
                            <div class="card card-plain">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Crear - Catalago</h4>
                                    <p class="category">Creación de Catalago</p>
                                    
                                </div>
                                <div class="pull-left">
                                         <a href="{{route('category.index')}}" class="btn btn-warning" id="addButton">Atrás</a>
                                    </div>
                                    <br>
                                    <br>
                                    <br>   
                                    <form action="{{ route('category.store') }}" method="POST"  enctype="multipart/form-data">
                                       {{ csrf_field() }}
                                      <div class="form-group">
                                         <label for="exampleInput1" class="bmd-label-floating">Nombre</label>
                                         <input type="text" name="name" class="form-control" id="description">
                                         <span class="bmd-help">Descripción de catalago</span>
                                      </div>
                                      <div class="form-group">
                                         <label for="exampleInput1" class="bmd-label-floating">Descripción</label>
                                         <input type="text" name="description" class="form-control" id="description">
                                         <span class="bmd-help">Descripción de catalago</span>
                                      </div>
                                     <div class="form-group">
                                        <label for="type">tipo</label>
                                        <select class="form-control" name="type" id="type">
                                          <option value="ingreso">INGRESO</option>
                                          <option value="egreso">EGRESO</option>
                                        </select>
                                    </div>
                                      <button type="submit" class="btn btn-primary">Guardar</button>
                                    </form> 
                               
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div> 
        </div>
  

@endsection

resources/views/category/edit.blade.php
@extends('layouts.master')

@section('content')
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                          <div class="col-md-12">
                            <div class="card card-plain">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Editar - Catalago</h4>
                                    <p class="category">Edición de Catalago</p>
                                    
                                </div>
                                <div class="pull-left">
                                         <a href="{{route('category.index')}}" class="btn btn-warning" id="addButton">Atrás</a>
                                    </div>
                                    <br>
                                    <br>
                                    <br>   
                                    <form action="{{ route('category.update', $category->id) }}" method="POST">
                                      {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="PUT">
                                      <div class="form-group">
                                         <label name="description" for="exampleInput1" class="bmd-label-floating">Nombre</label>
                                         <input name="name" type="text" class="form-control" id="description" value="{{$category->name}}">
                                         <span class="bmd-help">Nombre de catalago</span>
                                      </div>
                                      <div class="form-group">
                                         <label name="description" for="exampleInput1" class="bmd-label-floating">Descrpción</label>
                                         <input name="description" type="text" class="form-control" id="description" value="{{$category->description}}">
                                         <span class="bmd-help">Descripción de catalago</span>
                                      </div>
                                     <div class="form-group">
                                        <label for="type">tipo</label>
                                        <select name="type" class="form-control" id="type">
                                          <option value="ingreso">Ingreso</option>
                                          <option value="egreso">Egreso</option>
                                        </select>
                                    </div>
                                      <button type="submit" class="btn btn-primary">Guardar</button>
                                    </form> 
                               
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div> 
        </div>
  

@endsection

resources/views/category/index.blade.php
@extends('layouts.master')

@section('content')
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                          <div class="col-md-12">
                            <div class="card card-plain">
                                <div class="card-header" data-background-color="purple">
                                    <h4 class="title">Catalogos</h4>
                                    <p class="category">Listado de Catalagos</p>
                                    
                                </div>
                                <div class="pull-left">
                                         <a href="{{route('category.create')}}" class="btn btn-primary" id="addButton">Nuevo</a>
                                    </div>
                                    <br>
                                    <br>
                                    <br>    
                                <div class="card-content table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <th>Codigo</th>
                                            <th>Nombre</th>
                                            <th>Descripción</th>
                                            <th>Tipo</th>
                                            <th>Acciones</th>
                                        </thead>
                                        <tbody>
                                        @foreach($categories as $element)
                                        <tr>
                                            <td>{{$element -> id}}</td>
                                            <td>{{$element -> name}}</td>
                                            <td>{{$element -> description}}</td> 
                                            <td>{{$element -> type}}</td>   
                                            <td>
                                                <a href="{{route('category.edit',$element-> id)}}"><i class="material-icons text-info">mode_edit</i></a> 
                                            <form action="{{ route('category.destroy', $element->id) }}" method="POST"> 
                                        {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button type="submit"><i class="material-icons text-danger" >delete</i></button>
                                            </form></td>             
                                        </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div> 
        </div>
  

@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
    <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-sm-6">
                            <div class="card card-stats">
                                <div class="card-header" data-background-color="orange">
                                    <i class="material-icons">content_copy</i>
                                </div>
                                <div class="card-content">
                                    <p class="category">Used Space</p>
                                    <h3 class="title">49/50
                                        <small>GB</small>
                                    </h3>
                                </div>
                                <div class="card-footer">
                                    <div class="stats">
                                        <i class="material-icons text-danger">warning</i>
                                        <a href="#pablo">Get More Space...</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6">
                            <div class="card card-stats">
                                <div class="card-header" data-background-color="green">
                                    <i class="material-icons">store</i>
                                </div>
                                <div class="card-content">
                                    <p class="category">Revenue</p>
                                    <h3 class="title">$34,245</h3>
                                </div>
                                <div class="card-footer">
                                    <div class="stats">
                                        <i class="material-icons">date_range</i> Last 24 Hours
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6">
                            <div class="card card-stats">
                                <div class="card-header" data-background-color="red">
                                    <i class="material-icons">info_outline</i>
                                </div>
                                <div class="card-content">
                                    <p class="category">Fixed Issues</p>
                                    <h3 class="title">75</h3>
                                </div>
                                <div class="card-footer">
                                    <div class="stats">
                                        <i class="material-icons">local_offer</i> Tracked from Github
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6">
                            <div class="card card-stats">
                                <div class="card-header" data-background-color="blue">
                                    <i class="fa fa-twitter"></i>
                                </div>
                                <div class="card-content">
                                    <p class="category">Followers</p>
                                    <h3 class="title">+245</h3>
                                </div>
                                <div class="card-footer">
                                    <div class="stats">
                                        <i class="material-icons">update</i> Just Updated
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>   
                </div>
            </div> 

@endsection

resources/views/layouts/footer.blade.php
<footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="#">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Blog
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>
                        <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                    </p>
                </div>
</footer>